### ISSUE TITLE
RFC: Markdown que explica o assunto renomeado para README.md

### ISSUE THREAD

**Issue by lucasew** [wwwbrunagon/encontrocomJS#3]
Quando você está em uma pasta no repositório e essa pasta tem um README.md, o conteúdo deste fica renderizado embaixo da lista de arquivos.

[Exemplo](https://github.com/lucasew/playground/tree/master/vercel/redirect_to)

Eu posso mandar o PR sem problemas, só quero saber o que tu acha que eu faço tudo de uma vez e mando um outro PR depois do #2

**Comment by wwwbrunagon** [comment]
Eu acho super válido a contribuição . =)
